### ISSUE TITLE
Windows version of GUI?

### ISSUE THREAD

**Issue by jydong123** [elgw/deconwolf#61]
Hello, would greatly appreciate if the windows version of deconwolf can be made more accessible with GUI. Thanks so much!

**Comment by elgw** [comment]
Hi, I agree :) 

It is on the todo list, but unfortunately not with a very priority.

Cheers
Erik

**Comment by elgw** [comment]
There is a downloadable installer for windows available under [releases](https://github.com/elgw/deconwolf-gui/releases/). If you have any issues or suggestions about the gui please open a new [issue](https://github.com/elgw/deconwolf-gui/issues) in the [deconwolf-gui](https://github.com/elgw/deconwolf-gui/) repository.

Cheers,
Erik
