### ISSUE TITLE
PSF of individual FOV

### ISSUE THREAD

**Issue by pakiessling** [elgw/deconwolf#63]
Hi there,

congrats on the publication. This looks like an awesome tool and I will definetly try it out on our FISH data.

I have a silly question: 

I have a couple thousand FOV from an imaging run. 
Would I need to calculate the PSF for every separate image?

**Comment by elgw** [comment]
Hello, and thanks!

You only need to generate the PSF once, then it can be used for any image with the corresponding optical configuration (NA, ni, dx, dz, lambda). 

I guess that you use more than one channel/color. In that case you need as many PSFs as channels.

Cheers
Erik

**Comment by pakiessling** [comment]
Ty!
