### ISSUE TITLE
Incorrect output and log file paths when input image is in the current directory and output file is not specified

### ISSUE THREAD

**Issue by bluerose73** [elgw/deconwolf#70]
## Bug Description

The program "dw" generates incorrect output and log file paths under the following conditions:
- The input image is located in the current directory and we don't prefix it with ``.\``
- The output file is not specified.

## Steps to Reproduce

OS: Windows 11

```
cd demo
dw_bw --resxy 130 --resz 300 --lambda 461 --NA 1.45 --ni 1.512 PSF_dapi.tif --overwrite --nslice 79
dw --iter 20 dapi_001.tif PSF_dapi.tif --overwrite --noplan
```

Result:

**In release mode**
```
2024-06-20T09:17:16
> Settings:
image:  dapi_001.tif
psf:    PSF_dapi.tif
output: \dw_dapi_001.tif
log file: \dw_dapi_001.tif.log.txt
nIter:  20
nThreads for FFT: 10
nThreads for OMP: 10
verbosity: 1
background level: auto
method: Scaled Heavy Ball (SHB)
metric: Idiv
Stopping after 20 iterations
overwrite: YES
tiling: OFF
XY crop factor: 0.001000
Offset: 5.000000
Output Format: 16 bit integer
Scaling: Automatic
Border Quality: 2 Minimal boundary artifacts
FFT lookahead: 0
FFTW3 plan: FFTW_ESTIMATE (--noplan)
Initial guess: Flat average
deconwolf: '0.4.2'
BUILD_DATE: 'Jun 20 2024'
TIFF Backend: 'LIBTIFF, Version 4.6.0
Copyright (c) 1988-1996 Sam Leffler
Copyright (c) 1991-1996 Silicon Graphics, Inc.'
OpenMP: YES
OpenCL: YES
VkFFT: YES
```
Then the program exits.

**In debug mode**
```
Assertion failed: s->log != NULL, file C:\PATH_TO_REPO\deconwolf\src\dw.c, line 1983
```
It seems the program can't create the log file because it doesn't have permission to write in the root directory.

## Cause

The program incorrectly constructs the output file path by concatenating the input image directory (which is empty when the image is in the current directory), a path separator, and the output file name. As a result, the output path begins with a path separator ``\``, leading to the root directory.

**Comment by elgw** [comment]
Hello,

Thank you for the very clear bug report! 

Looks like something that can be fixed :) Planned for next week.

Cheers,
Erik

**Comment by elgw** [comment]
Hello,

The issue should be solved with the latest version. Thanks again for reporting!

Cheers,
Erik

## Details
The programmer wasn't aware of all the pitfalls under windows and naively/lazily tried to re-use as much of the linux code as possible. From now on files are prefixed by a combination of [_makepath](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/makepath-wmakepath?view=msvc-170) and [_splitpath](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/splitpath-wsplitpath?view=msvc-170).

**Comment by bluerose73** [comment]
Hi, I can confirm that the issue is solved on my machine. Thank you for the prompt fix!
