### ISSUE TITLE
How to set P (number of slices) in dw_bw tool ?

### ISSUE THREAD

**Issue by xqzh268** [elgw/deconwolf#79]
![image](https://github.com/user-attachments/assets/c9466a37-6c9a-4134-8a47-55303a06aabb)

Hii, I wonder how do I set the parameter ‘P’ in `dw_bw --resxy 65 --resz 200 --NA 1.45 --ni 1.515 --lambda 466 PSF_DAPI.tif` ?
I've tried many forms but failed, like `--slices 89` or `--P 89`

**Comment by xqzh268** [comment]
solved, should be `--nslice 89` 😂

**Comment by elgw** [comment]
Good that you found the solution:) 

I fixed the help message in the man page, it will be correct in the next version.  It was already correct in `dw_bw --help`.

In general it does not matter for `dw` if there are more slices than necessary, they will be cropped away when the PSF is read.

**Comment by xqzh268** [comment]
OK👌, get it! **Thanks very much** for answering! 😀
